name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *" # Chạy tự động mỗi ngày lúc 0h UTC
  workflow_dispatch:    # Cho phép tự bấm "Run workflow" trên GitHub

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Snake Animation
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/snake.svg

      - name: Push snake.svg to profile
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "Generate Snake Animation"
          add: "dist/snake.svg"
